"""added cancelled classes

Revision ID: 99eab19c8e24
Revises: a923116aad9b
Create Date: 2022-02-13 19:36:18.883910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eab19c8e24'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canceled classes',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('block', sa.String(length=8), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['teachers.tid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tid', 'block', 'date', 'uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canceled classes')
    # ### end Alembic commands ###
