"""initial

Revision ID: eb63a2e485eb
Revises: 
Create Date: 2022-02-23 11:51:46.817175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb63a2e485eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelled',
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.add_column('classes', sa.Column('cid', sa.String(length=36), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'cid')
    op.drop_table('cancelled')
    # ### end Alembic commands ###
