"""timestamps for sessions

Revision ID: 2e93bd18dfa5
Revises: a2fe6e36df2c
Create Date: 2022-01-19 17:09:36.045979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e93bd18dfa5'
down_revision = 'a2fe6e36df2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('sid', sa.String(length=16), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
