"""partitions

Revision ID: 3295880a84ee
Revises: 564c342470c4
Create Date: 2022-01-21 09:52:56.839980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3295880a84ee'
down_revision = '564c342470c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
