"""first rev

Revision ID: 564c342470c4
Revises: da9feaacb4c3
Create Date: 2022-01-21 09:34:51.430431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c342470c4'
down_revision = 'da9feaacb4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('fcm_timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'fcm_timestamp')
    op.drop_column('sessions', 'fcm_token')
    # ### end Alembic commands ###
