"""test

Revision ID: 60aaceeb96fd
Revises: 0b2111371444
Create Date: 2022-01-18 21:22:01.966176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60aaceeb96fd'
down_revision = '0b2111371444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    # ### end Alembic commands ###
