"""test revert

Revision ID: 706ea55f30ef
Revises: 60aaceeb96fd
Create Date: 2022-01-18 21:22:21.037840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706ea55f30ef'
down_revision = '60aaceeb96fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
