"""uniques for teacher

Revision ID: 9dbdd3a263ba
Revises: f3466836da71
Create Date: 2022-01-19 17:03:20.975038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbdd3a263ba'
down_revision = 'f3466836da71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teachers', ['first', 'last', 'school'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    # ### end Alembic commands ###
