"""timestamps for sessions

Revision ID: a2fe6e36df2c
Revises: 9dbdd3a263ba
Create Date: 2022-01-19 17:07:00.741956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fe6e36df2c'
down_revision = '9dbdd3a263ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
