"""changed TID formatting

Revision ID: da9feaacb4c3
Revises: 2e93bd18dfa5
Create Date: 2022-01-19 17:48:53.549887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9feaacb4c3'
down_revision = '2e93bd18dfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('first', sa.String(length=255), nullable=True),
    sa.Column('last', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('first', 'last', 'school')
    )
    op.create_table('absences',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['teachers.tid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tid', 'date')
    )
    op.create_table('classes',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('block', sa.String(length=8), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['teachers.tid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tid', 'block', 'uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    op.drop_table('absences')
    op.drop_table('teachers')
    # ### end Alembic commands ###
