"""partitions

Revision ID: f3466836da71
Revises: be2a5fc73aaa
Create Date: 2022-01-19 16:55:41.210608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3466836da71'
down_revision = 'be2a5fc73aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
