"""empty message

Revision ID: f02bd984465a
Revises: 
Create Date: 2022-02-24 12:07:43.881645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02bd984465a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('first', sa.String(length=255), nullable=True),
    sa.Column('last', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('first', 'last', 'school')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('gid', sa.String(length=255), nullable=True),
    sa.Column('first', sa.String(length=255), nullable=True),
    sa.Column('last', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=4), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('gid')
    )
    op.create_table('absences',
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['teachers.tid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tid', 'date')
    )
    op.create_table('classes',
    sa.Column('cid', sa.String(length=16), nullable=False),
    sa.Column('tid', sa.String(length=8), nullable=False),
    sa.Column('block', sa.String(length=8), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['teachers.tid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'tid', 'block', 'uid')
    )
    op.create_table('sessions',
    sa.Column('sid', sa.String(length=16), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('fcm_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'uid')
    )
    op.create_table('cancelled',
    sa.Column('cid', sa.String(length=16), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['classes.cid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('sessions')
    op.drop_table('classes')
    op.drop_table('absences')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('cancelled')
    # ### end Alembic commands ###
